terminal:
  colorScheme:
    name: MaterialDark
    foreground: '#e5e5e5'
    background: '#232322'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#424242'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  environment: {}
  profile: git-bash
  searchOptions: {}
  workingDirectory: C:\Users\Andreas\git
  alwaysUseWorkingDirectory: true
hotkeys:
  profile: {}
  toggle-window:
    - - F1
  shell: {}
serial: {}
ssh: {}
appearance:
  vibrancyType: fluent
  dock: top
  opacity: 1
  vibrancy: false
  theme: Compact
  frame: thin
  dockAlwaysOnTop: true
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
