if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

if [ -f ~/.ssh_gpg_agent ]; then
  . ~/.ssh_gpg_agent
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# Don't put duplicate lines in the history and do not add lines that start with a space
export HISTCONTROL=erasedups:ignoredups:ignorespace

export GPG_TTY=$(tty)

# Install Starship - curl -sS https://starship.rs/install.sh | sh
eval "$(starship init bash)"